/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package com.robertof;

/**
 *
 * @author Roberto
 */
public class AutoUpdateGUI extends javax.swing.JFrame {
    private GUI mainClass;
    private Thread t1;
    private boolean threadHasToStop = false;
    public AutoUpdateGUI(GUI mC) {
        initComponents();
        mainClass = mC;
        mainClass.setEnabled(false);
        t1 = new Thread (new Runnable(){
            @Override
            public void run() {
                // this thread checks the spinner value
                while (true)
                {
                    if (threadHasToStop)
                    {
                        threadHasToStop = false;
                        return;
                    }
                    // get spinner value
                    try {
                        int value = Integer.parseInt(jSpinner1.getValue().toString());
                        if (value < 0 || value == 0)
                            jSpinner1.setValue(1);
                        Thread.sleep(300);
                    }
                    catch (NumberFormatException e)
                    {
                        jSpinner1.setValue(1);
                    }
                    catch (InterruptedException e)
                    {}
                }
            } 
        });
        t1.start();
        if (mainClass.timerFreq > 0 && mainClass.existingTimer != null && mainClass.existingTimer.isAlive())
        {
            // update our fields with the values in the mainthread
            autoUpdButton.setSelected(true);
            if (mainClass.timerFreq < 60)
            {
                System.out.println("Setting to => " + mainClass.timerFreq);
                jSpinner1.setValue(mainClass.timerFreq);
            }
            else if (mainClass.timerFreq > 60 && mainClass.timerFreq < 3600)
            {
                jSpinner1.setValue(Math.round(mainClass.timerFreq / 60));
                jComboBox1.setSelectedIndex(1);
            }
            else if (mainClass.timerFreq > 3600 && mainClass.timerFreq < 86400)
            {
                jSpinner1.setValue(Math.round(mainClass.timerFreq / 3600));
                jComboBox1.setSelectedIndex(2);
            }
            else if (mainClass.timerFreq > 86400)
            {
                jSpinner1.setValue(Math.round(mainClass.timerFreq / 86400));
                jComboBox1.setSelectedIndex(3);
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        autoUpdButton = new javax.swing.JToggleButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox();
        jSpinner1 = new javax.swing.JSpinner();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Impostazioni sull'autoaggiornamento");
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        autoUpdButton.setText("Attiva autoaggiornamento");

        jLabel1.setText("Frequenza di autoaggiornamento:");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Secondi", "Minuti", "Ore", "Giorni" }));

        jSpinner1.setValue(1);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jSpinner1, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSpinner1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        jButton1.setText("Chiudi");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(autoUpdButton)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(autoUpdButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        formWindowClosing(null);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        if (t1.isAlive())
        {
            threadHasToStop = true;
            t1.interrupt();
        }
        if (autoUpdButton.isSelected())
        {
            // check again if data is valid
            try {
                int value = Integer.parseInt(jSpinner1.getValue().toString());
                if (value <= 0)
                    throw new NumberFormatException();
                // register the timer
                // get the real value in seconds
                int multiplier = 1;
                if (jComboBox1.getSelectedIndex() == 1) // minutes
                    multiplier = 60;
                else if (jComboBox1.getSelectedIndex() == 2) // hours
                    multiplier = 3600;
                else if (jComboBox1.getSelectedIndex() == 3) // days
                    multiplier = 86400;
                mainClass.registerTimer(value * multiplier);
                System.out.println ("Timer d" + (value * multiplier) + " registered");
            } catch (NumberFormatException e)
            {
                Main.throwError("Impossibile impostare un valore per il timer.");
            }
        }
        else
        {
            // try to unregister timer
            mainClass.unregisterTimer();
        }
        mainClass.setEnabled(true);
        this.setVisible(false);
        this.dispose();
    }//GEN-LAST:event_formWindowClosing

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton autoUpdButton;
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSpinner jSpinner1;
    // End of variables declaration//GEN-END:variables
}
